# Generated by Django 2.0.13 on 2019-04-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('approve_comment', 'Can approve a comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('publish_post', 'Can publish a draft post'), ('view_draft_posts', 'Can view draft posts')]},
        ),
    ]
